### ISSUE TITLE
Save EVO TOF sensor data when flying 

### ISSUE THREAD

**Issue by Yuanbwcx** [QUB-ASL/bzzz#188]
### Describe the solution you'd like

Be able to save Evo TOF data to check if the sensor work while flying

**Comment by jamie-54** [comment]
@alphaville @Yuanbwcx I think this issue was just to check that the EVO time of flight sensor works while flying. This has been tested and works. I can push the branch and make a PR but I'm not sure if it will be worth merging as it is only a few lines of code that'll need changed anyway?

Maybe we should make a new issue outlining what @alphaville has mentioned above?

**Comment by Yuanbwcx** [comment]
@alphaville Yes, sir I will take care of it. Are we gonna replace the old sensor or use both at the same time?

**Comment by alphaville** [comment]
@Yuanbwcx as a first priority I would simply replace the old sensor with the new one.

**Comment by alphaville** [comment]
This is being addressed in #194

**Comment by jamie-54** [comment]
Should we close this?

**Comment by jamie-54** [comment]
Done
